load_if_exists( Rails.root.join( 'db', 'seeds', 'seed_files', 'functions.rb' ) )
load_if_exists( Rails.root.join( 'db', 'seeds', 'seed_files', 'store_setup.rb' ) )
load_if_exists( Rails.root.join( 'db', 'seeds', 'seed_files', 'shipping.rb' ) )
load_if_exists( Rails.root.join( 'db', 'seeds', 'seed_files', 'products.rb' ) )
load_if_exists( Rails.root.join( 'db', 'seeds', 'seed_files', 'galleries.rb' ) )
